# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dfa8c435b1f2241d180a776890d4d4db9077629fe997e2993767fd2b622226b8a8bd268bac86d49cdcc6031903aba2dc1bcf03c4346e8028a8b1f7f791ee4a3e

test:
  secret_key_base: 45f719f13d720947115bb77b789167e9ecd8006438725c190fd1d9f4e8c8ad9cd47a21586e9dad7417bb48f3eda80e33f5756bec57ff71e812e44dbbc83ee13e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
